[project]
authors = ["larry <xspanni@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "hello-world"
platforms = ["linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
